### ISSUE TITLE
Blank screen on iOS and stuck on splashscreen on Android

### ISSUE THREAD

**Issue by chrisvanderkooi** [ionic-team/cordova-plugin-ionic#109]
Currently since the update of `cordova-plugin-ionic-webview` to version `2.0.0`, our app has had nothing but issues. We haven't been able to get the templates to show in our app anymore.

We decided to create a new app using `ionic start`. We used the package and cordova plugin values from the new app in our app. I could not replicate what we were seeing, so in the new app, I added the `cordova-plugin-ionic` plugin with our deploy credentials. That's where the problem *seems* to lie.

On Android, the blank app I created is stuck at the splash screen. I hooked up to the app via the chrome device console and found this:
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
deviceready has not fired after 5 seconds.
Ionic Native: deviceready event fired after 4894 ms
calling _sync
Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
Install the StatusBar  plugin: 'ionic cordova plugin add cordova-plugin-statusbar'
calling _reload
Unhandled Promise rejection: Cannot read property 'getServerBasePath' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'getServerBasePath' of undefined
    at IonicDeployImpl.<anonymous> (common.js:377)
    at Generator.next (<anonymous>)
    at common.js:11
    at new t (polyfills.js:3)
    at __awaiter (common.js:7)
    at Promise (common.js:375)
    at new t (polyfills.js:3)
    at IonicDeployImpl.<anonymous> (common.js:375)
    at Generator.next (<anonymous>)
    at common.js:11 TypeError: Cannot read property 'getServerBasePath' of undefined
    at IonicDeployImpl.<anonymous> (file:///android_asset/www/plugins/cordova-plugin-ionic/dist/common.js:377:35)
...
```
This is output of `cordova plugin list`:
```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic 5.0.3 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
Here is my `ionic info` output:
```
Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0, ios 4.5.5

System:

   ios-deploy : 1.9.2
   ios-sim    : 5.0.6
   NodeJS     : v8.9.1 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

Again, this is a fresh, blank project but the difference is we are using Ionic Deploy with our own app credentials.

**Comment by Bengejd** [comment]
Running into this same issue on IOS. The application works the first time you open it on downloading it from the App store, but after that, it just shows a blank white screen that never leaves.

**Comment by Bengejd** [comment]
After a bit of digging, it seems that the following errors are being thrown within the vendor.js file and main.js

<img width="354" alt="screen shot 2018-07-29 at 9 55 20 pm" src="https://user-images.githubusercontent.com/11723093/43373839-3ec24cf6-937a-11e8-9973-5d825e7c334b.png">

**Comment by MumblesNZ** [comment]
I'm getting the same error with android, 
`Unhandled Promise rejection: Cannot read property 'getServerBasePath' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'getServerBasePath' of undefined`

**Comment by nphyatt** [comment]
The error `Cannot read property 'getServerBasePath' of undefined ;` suggests that for some reason the `cordova-plugin-ionic-webview` isn't available which would indeed cause the app to be unable to load past the splash screen. I will need to investigate whether it is an issue with the deploy plugin needing to wait for the webview plugin to be ready or an issue with the webview plugin.

**Comment by chrisvanderkooi** [comment]
Fixed with a recent version release of `cordova-plugin-ionic-webview`

**Comment by ngware** [comment]
Up!I have the same issue here :/

**Comment by EvanSpielman** [comment]
I also still have the same issue.

**Comment by nharrer** [comment]
I am still having this problem as of this date (ionic cli 4.1.2.), when I start a fresh project with ionic start. After installing cordova-plugin-ionic and running the android build for the first time there is this message: 

```
Installing "cordova-plugin-ionic-webview" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=6.4.0
```

This is what I had to to: 

1. Change version of cordova-android in package.json to 6.4.0: `"cordova-android": "6.4.0",`
2. Change version of android in config.xml: `<engine name="android" spec="6.4.0" />`
3. Delete  node_modules and platform
4. `npm i`
5. deinstall the app from the phone if it is already installed
6. `ionic cordova run android`

I don't know why step 5 is needed. But I still had the error after having build and deployed the app with cordova-android 6.4.0. It only started working after a deinstalled / reinstall.

**Comment by neilodiaz** [comment]
Any update on this? I still have the same issue. 

`Unhandled Promise rejection: Cannot read property 'getServerBasePath' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'getServerBasePath' of undefined`

Thanks!

**Comment by Shadowstep33** [comment]
@nharrer it seems ionic-cordova-plugin-webview@3.0.0 only supports android@6.4.0+

**Comment by AmyJUn** [comment]
same issue here in IOS.

was going to install the latest but 

cordova plugin add cordova-plugin-ionic-webview@latest

Fetching plugin "cordova-plugin-ionic-webview@latest" via npm
Installing "cordova-plugin-ionic-webview" for ios
Plugin doesn't support this project's cordova version. cordova: 6.5.0, failed version requirement: >=7.1.0
Skipping 'cordova-plugin-ionic-webview' for ios

**Comment by AmyJUn** [comment]
yes, i had issues before and upgrade it then it fixed.

**Comment by AmyJUn** [comment]
and yes i did update cordova too. thanks @jcesarmobile

**Comment by udayghulaxe** [comment]
I am facing the same issue as of date. Ionic CLI version 5.4.2.
I have installed the fresh ionic project with side menu. App is working fine without any console errors in the browser but getting only white screen after initial splash screen.
I tried removing all node modules and installing again and upgrading version of "cordova-plugin-ionic-webview" to latest 4.1.2 version but no luck.

This is my ionic info
`Ionic:

   Ionic CLI                     : 5.4.2 (C:\Users\ughulaxe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10`
