### ISSUE TITLE
App starts with original snashot. Also after update

### ISSUE THREAD

**Issue by flyingwip** [ionic-team/cordova-plugin-ionic#120]
App starts with original snashot. Also after update.

I found out the following scenario happens after an live update has took place:

TWhen the app is installed the apps starts up quite regularly with a splashscreen for about 3 seconds
and then the app is ready for the user to start. 

If there is an update and the user installs the update (approx 10-15 seconds) everything is working fine and we can see the changes we have made in the app. 

However if the user again starts the app , the app needs much more time to start , resulting in a longer display of the splash screen or even a white screen. The app needs now for about 10-15 seconds to start. 
This to our surprise because the app has updated already. 

After some debugging I found out that the app starts with the original source code. 
It then sees there is a .more recent version (locally!!, it can tell by the snaspshot info), and 
then reloads the app to the more recent version. This reloading takes about 10-15seconds. 

In our case this is too much time to take our app into production with this feature.

Is there a way that the app can start with the most recent snapshop by default?

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.2
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\****\AppData\Local\Android\sdk

Misc:

    backend : pro

**Comment by diegozuber** [comment]
I can confirm that issue. I've tested on an iPhone 6. With v4.1.x I had startup time around 3 seconds. With v5 I have startup times around 10 seconds on the same device. On newer devices it's no as noticeable as on the older ones.

**Comment by ibnclaudius** [comment]
I can also confirm the issue, I'm facing exactly the same problem running on Android.

1. The application starts with the original snapshot.
2. We release a new update on the channel.
3. The update is downloaded in the background.
4. The update is installed the next time the application starts.
5. After updating, the app keeps starting with the original snapshot, but takes a little longer on the splash screen and updates to the latest snapshot **again**.
6. This behavior continues all the time that the application starts after it has updated the first time.

As stated by @flyingwip, in my case it's also a long waiting time to launch into production.

My settings:

Ionic:
```
ionic (Ionic CLI)  : 4.0.6 (/Users/ibnclaudius/.config/yarn/global/node_modules/ionic)
Ionic Framework    : ionic-angular 3.9.2
@ionic/app-scripts : 3.1.11
```

Cordova:
```
cordova (Cordova CLI) : 8.0.0
Cordova Platforms     : none
```

System:
```
NodeJS : v9.11.2 (/Users/ibnclaudius/.nvm/versions/node/v9.11.2/bin/node)
npm    : 5.6.0
OS     : macOS High Sierra
```

package.json:
```
{
  "name": "my-app",
  "version": "0.0.1",
  "author": "Claudius Ibn",
  "homepage": "https://myhomepage.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.11.0",
    "@ionic-native/splash-screen": "~4.11.0",
    "@ionic-native/status-bar": "~4.11.0",
    "@ionic/pro": "^2.0.3",
    "@ionic/storage": "2.1.3",
    "cordova-plugin-ionic": "^5.0.5",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.11",
    "typescript": "~2.6.2"
  },
  "description": "An awesome app.",
  "cordova": {
    "plugins": {
      "cordova-plugin-ionic": {
        "APP_ID": "<MY_APP_ID>",
        "CHANNEL_NAME": "Production",
        "UPDATE_METHOD": "background",
        "WARN_DEBUG": "true"
      }
    }
  }
}
```

**Comment by Fuiste** [comment]
Hey all, it's possible this is a result of the way we're locally rebuilding updates when a binary change happens.  I've pushed 5.0.6, which may speed up the redirect process quite a bit in this case.

Try it out and let me know if it helps.

**Comment by 2mia** [comment]
@Fuiste that didn't change. I can provide exact details if you need, but the gist is:
- it starts the web server with path "www"
- checks the last snapshot available and gets a UUID value
- forces a reload.

The app constructor in my case gets called twice. You can debug that on Android easier than on Safari/iOS

**Comment by Fuiste** [comment]
Gotcha.  Unfortunately, the redirect-on-start portion of Deploy is essential to the functionality (as we can't replace the resources that came bundled in the app, it's againse ToS), but we're actively looking into any way we can to make it as fast as possible.

**Comment by 2mia** [comment]
i kind of though that was the case :)

But this behavior is unexpected and can potentially lead to negative impact on certain apps; imagine double login, responses to push notifications... etc. Ionic should make this clear or document a “waitOnUpdateStatus” event the app should wait, instead of “onDeviceReady”.

**Comment by nphyatt** [comment]
@2mia so even with `5.0.6` it looks like there was a bug where the app was still being reconstructed on every app open. I highly suspect that that is the issue causing the slow down and not the actual reload itself as serving from the local file system should not take anywhere near that long. I just release `5.0.7` which should fix the issue can you try that and let me know if it solves?

As far as the reload itself goes it would require a change to `cordova-plugin-ionic-webview` in order to support not serving the updated version. As mentioned above we can't overwrite the bundled version of the app because the OS makes that read only. Right now `cordova-plugin-ionic-webview` serves the original version of the app always but exposes an API for redirecting to server a different version of the app from a location on the filesystem of the device. It could potentially save that state and remember to serve the last version passed to the API on startup but that comes with some tradeoffs. For example if you were to launch an update that broke your app entirely you would not be able to recover from it by launching a fix via live update. Currently there is a built in safety net in that as long as your original version worked it will launch the deploy plugin code from that version check for an update and apply the latest. Therefore you could temporarily deploy a broken update but with the original code would alway run and pick up any fix you deploy. If the device defaulted to the broken update there would be no way to fix it except for the user to delete the app and re-install.

Hopefully `5.0.7` fixes the speed issue and we'll need to look into and think about the reload issue.

**Comment by ibnclaudius** [comment]
I updated to version `5.0.7` and tested the deploy flow again Ref: https://github.com/ionic-team/cordova-plugin-ionic/issues/120#issuecomment-413091386. The problem of version `5.0.5` still exists, after the splashscreen with the loading spinner closes, it opens again for about 4 seconds, but this time without the loading spinner. The only difference I noticed between the updates is that before it was possible to see between the transitions of the splashscreens the app with the original snapshot.

**Comment by nphyatt** [comment]
@ibnclaudius what does taking a little longer mean exactly? are we still talking 10-15 seconds or 1 or 2 seconds?

**Comment by nphyatt** [comment]
@diegozuber @flyingwip does upgrading help solve the issue for you? (`5.0.9` is now latest FYI)

If not is everyone using `background` for the update method? having trouble reproducing...

**Comment by ibnclaudius** [comment]
@nphyatt In my case about `4 seconds`, I'm testing a text update on a single component. I'm using the method `background`. I'll test with `5.0.9`.

**Comment by mikeciavHB** [comment]
I am having this same issue ??  If I were to go down to a 5.0.3???? version would that solve the issue ?   I am in a serious jam and need to deploy next week.  If the only solution is to remove ionic pro altogether will some on please let us know.   If i do a fresh install my app works.   The next time the app goes to get a new version from ionic servers and do  update the app crashes and i get a white splash screen... I was having no issues 2 weeks ago and raving about ionic .... I am seeing this issue more and hope this gets resolved soon.  Or just let us know that we can remove ionic pro and it wont happen but i have been unsuccessful doing thats well.   Sorry its late and i am very frustrated this is like 5th day in a row .    I have attached my ionic info and also my XCODE logs.  and package.json
IONIC INFO:
----

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.0.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v10.5.0
    npm        : 6.2.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro



---
XCODE LOGS ----

2018-08-16 22:48:24.584191-0700 WorkPlay[3176:42087] Apache Cordova native platform version 4.5.5 is starting.
2018-08-16 22:48:24.585096-0700 WorkPlay[3176:42087] Multi-tasking -> Device: YES, App: YES
2018-08-16 22:48:24.600298-0700 WorkPlay[3176:42087] CDVWKWebViewEngine: trying to inject XHR polyfill
2018-08-16 22:48:24.685865-0700 WorkPlay[3176:42087] CDVWKWebViewEngine will reload WKWebView if required on resume
2018-08-16 22:48:24.686100-0700 WorkPlay[3176:42087] Using Ionic WKWebView
2018-08-16 22:48:24.686938-0700 WorkPlay[3176:42087] [CDVTimer][console] 0.118017ms
2018-08-16 22:48:24.687377-0700 WorkPlay[3176:42087] [CDVTimer][handleopenurl] 0.216007ms
2018-08-16 22:48:24.690679-0700 WorkPlay[3176:42087] Unlimited access to network resources
2018-08-16 22:48:24.690940-0700 WorkPlay[3176:42087] [CDVTimer][intentandnavigationfilter] 3.358960ms
2018-08-16 22:48:24.691218-0700 WorkPlay[3176:42087] [CDVTimer][gesturehandler] 0.120044ms
2018-08-16 22:48:24.693467-0700 WorkPlay[3176:42087] [CDVTimer][file] 2.095103ms
2018-08-16 22:48:24.706911-0700 WorkPlay[3176:42087] [CDVTimer][splashscreen] 13.293982ms
2018-08-16 22:48:24.708116-0700 WorkPlay[3176:42087] [CDVTimer][ioniccordovacommon] 1.050949ms
2018-08-16 22:48:24.708339-0700 WorkPlay[3176:42087] CDVIonicKeyboard: resize mode 1
2018-08-16 22:48:24.709349-0700 WorkPlay[3176:42087] [CDVTimer][keyboard] 1.052976ms
2018-08-16 22:48:24.715413-0700 WorkPlay[3176:42087] [CDVTimer][statusbar] 5.923986ms
2018-08-16 22:48:24.722165-0700 WorkPlay[3176:42087] [CDVTimer][localnotification] 6.533027ms
2018-08-16 22:48:24.722367-0700 WorkPlay[3176:42087] [CDVTimer][localnotification] 0.014067ms
2018-08-16 22:48:24.722505-0700 WorkPlay[3176:42087] [CDVTimer][TotalPluginStartup] 35.760999ms
2018-08-16 22:48:27.473133-0700 WorkPlay[3176:42087] Got app info: {
    bundleName = "com.workplaywellness.WorkplayApp";
    bundleVersion = "3.3.4";
    device = "B1BC517F-63E7-4777-A10E-15CD05F8D3E9";
    platform = ios;
    platformVersion = "11.4";
    version = "3.3.4";
}
2018-08-16 22:48:27.473772-0700 WorkPlay[3176:42087] Ionic Native: deviceready event fired after 963 ms
2018-08-16 22:48:27.474805-0700 WorkPlay[3176:42087] WARN: This function has been deprecated in favor of IonicCordova.getAppDetails.
2018-08-16 22:48:27.482546-0700 WorkPlay[3176:42087] Found saved prefs: {
    appId = cf9e7264;
    availableUpdate =     {
        binaryVersion = "3.3.4";
        channel = Production;
        lastUsed = "2018-08-17T05:45:31.963Z";
        state = ready;
        url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff/manifest";
        versionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
    };
    binaryVersion = "3.3.4";
    channel = Production;
    currentVersionId = "54bab3e1-3da4-4159-b26a-2059a269a300";
    debug = true;
    host = "https://api.ionicjs.com";
    maxVersions = 2;
    minBackgroundDuration = 30;
    updateMethod = background;
    updates =     {
        "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-17T05:45:31.963Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff/manifest";
            versionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
        };
        "54bab3e1-3da4-4159-b26a-2059a269a300" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-15T00:19:06.016Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/54bab3e1-3da4-4159-b26a-2059a269a300/manifest";
            versionId = "54bab3e1-3da4-4159-b26a-2059a269a300";
        };
    };
}
2018-08-16 22:48:27.518018-0700 WorkPlay[3176:42087] Got app info: {
    bundleName = "com.workplaywellness.WorkplayApp";
    bundleVersion = "3.3.4";
    device = "B1BC517F-63E7-4777-A10E-15CD05F8D3E9";
    platform = ios;
    platformVersion = "11.4";
    version = "3.3.4";
}
2018-08-16 22:48:27.518402-0700 WorkPlay[3176:42087] ionViewWillEnter LoginPage
2018-08-16 22:48:27.522171-0700 WorkPlay[3176:42087] ionViewDidEnter LoginPage
2018-08-16 22:48:27.524765-0700 WorkPlay[3176:42087] -----------------Platform Ready  in LoginPage-------------------
2018-08-16 22:48:27.525517-0700 WorkPlay[3176:42087] -----------------Storage Ready  in LoginPage-------------------
2018-08-16 22:48:27.526320-0700 WorkPlay[3176:42087] Get Employee ID from Storage null
2018-08-16 22:48:27.559938-0700 WorkPlay[3176:42087] Got prefs to save: {
    appId = cf9e7264;
    binaryVersion = "3.3.4";
    channel = Production;
    currentVersionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
    debug = true;
    host = "https://api.ionicjs.com";
    maxVersions = 2;
    minBackgroundDuration = 30;
    updateMethod = background;
    updates =     {
        "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-17T05:45:31.963Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff/manifest";
            versionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
        };
        "54bab3e1-3da4-4159-b26a-2059a269a300" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-15T00:19:06.016Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/54bab3e1-3da4-4159-b26a-2059a269a300/manifest";
            versionId = "54bab3e1-3da4-4159-b26a-2059a269a300";
        };
    };
}
2018-08-16 22:48:27.566406-0700 WorkPlay[3176:42087] Found saved prefs: {
    appId = cf9e7264;
    binaryVersion = "3.3.4";
    channel = Production;
    currentVersionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
    debug = true;
    host = "https://api.ionicjs.com";
    maxVersions = 2;
    minBackgroundDuration = 30;
    updateMethod = background;
    updates =     {
        "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-17T05:45:31.963Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff/manifest";
            versionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
        };
        "54bab3e1-3da4-4159-b26a-2059a269a300" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-15T00:19:06.016Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/54bab3e1-3da4-4159-b26a-2059a269a300/manifest";
            versionId = "54bab3e1-3da4-4159-b26a-2059a269a300";
        };
    };
}
**_### 2018-08-16 22:48:27.573805-0700 WorkPlay[3176:42087] fetched current base path as /Users/mikeciavarelli/Library/Developer/CoreSimulator/Devices/DF8D9E30-E21C-4696-91C9-CB67A42BB7E5/data/Containers/Bundle/Application/F23E0716-6B2F-4F7E-B4D7-BB40A458C938/WorkPlay.app/www
2018-08-16 22:48:27.607289-0700 WorkPlay[3176:42087] ERROR: Unhandled Promise rejection: cancelled ; Zone: <root> ; Task: Promise.then ; Value: TypeError: cancelled
2018-08-16 22:48:28.342990-0700 WorkPlay[3176:42087] Found saved prefs: {_**
    appId = cf9e7264;
    binaryVersion = "3.3.4";
    channel = Production;
    currentVersionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
    debug = true;
    host = "https://api.ionicjs.com";
    maxVersions = 2;
    minBackgroundDuration = 30;
    updateMethod = background;
    updates =     {
        "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-17T05:45:31.963Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff/manifest";
            versionId = "1cc50af7-d7fc-437d-93b2-9c7f5a2e55ff";
        };
        "54bab3e1-3da4-4159-b26a-2059a269a300" =         {
            binaryVersion = "3.3.4";
            channel = Production;
            lastUsed = "2018-08-15T00:19:06.016Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/cf9e7264/snapshots/54bab3e1-3da4-4159-b26a-2059a269a300/manifest";
            versionId = "54bab3e1-3da4-4159-b26a-2059a269a300";
        };
    };
}

PACKAGE.JSON:
 "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@cloudinary/angular-5.x": "1.0.1",
    "@ionic-native/barcode-scanner": "4.11.0",
    "@ionic-native/calendar": "4.11.0",
    "@ionic-native/camera": "4.10.0",
    "@ionic-native/core": "4.10.0",
    "@ionic-native/crop": "4.10.0",
    "@ionic-native/file": "4.10.0",
    "@ionic-native/file-path": "4.10.0",
    "@ionic-native/health": "4.10.0",
    "@ionic-native/image-picker": "4.10.0",
    "@ionic-native/local-notifications": "4.10.0",
    "@ionic-native/splash-screen": "4.10.0",
    "@ionic-native/status-bar": "4.10.0",
    "@ionic-native/transfer": "3.14.0",
    "@ionic/pro": "2.0.3",
    "@ionic/storage": "2.1.3",
    "@types/cordova": "0.0.34",
    "@types/lodash": "4.14.108",
    "@types/moment-timezone": "^0.5.7",
    "angular2-moment": "1.9.0",
    "angular2-qrcode": "2.0.1",
    "cloudinary-core": "2.5.0",
    "cordova-android": "7.0.0",
    "cordova-ios": "4.5.5",
    "cordova-plugin-app-event": "1.2.1",
    "cordova-plugin-calendar": "5.1.2",
    "cordova-plugin-camera": "4.0.3",
    "cordova-plugin-crop": "0.4.0",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-ionic": "5.0.5",
    "cordova-plugin-ionic-keyboard": "2.0.5",
    "cordova-plugin-ionic-webview": "2.0.2",
    "cordova-plugin-ios-camera-permissions": "1.2.0",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.2",
    "cordova-plugin-whitelist": "1.3.3",
    "cordova-sqlite-storage": "2.3.1",
    "de.appplant.cordova.plugin.local-notification": "0.8.5",
    "font-awesome": "4.7.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "lodash": "4.17.10",
    "moment": "2.22.2",
    "moment-timezone": "0.5.21",
    "ng2-file-upload": "1.3.0",
    "phonegap-plugin-barcodescanner": "8.0.0",
    "run": "1.4.0",
    "rxjs": "5.5.6",
    "save": "2.3.2",
    "sw-toolbox": "3.6.0",
    "videogular2": "6.0.1",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/language-service": "6.0.7",
    "@ionic/app-scripts": "3.1.11",
    "@types/node": "10.5.4",
    "typescript": "2.6.2"
  },
  "description": "WorkPlay Wellness App",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-crop": {},
      "cordova-plugin-ios-camera-permissions": {
        "CAMERA_USAGE_DESCRIPTION": "This app needs camera access to post pictures to WorkPlay Activity Feed",
        "MICROPHONE_USAGE_DESCRIPTION": "This app needs microphone access for activity feed.",
        "PHOTOLIBRARY_ADD_USAGE_DESCRIPTION": "This app needs write-access to photo library for the WorkPlay activity feed.",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": "This app needs read/write-access photo library access for the Workplay activity feed."
      },
      "cordova-plugin-statusbar": {},
      "de.appplant.cordova.plugin.local-notification": {},
      "phonegap-plugin-barcodescanner": {},
      "cordova-plugin-calendar": {
        "CALENDAR_USAGE_DESCRIPTION": "WorkPlay app uses your calendar to save events"
      },
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic": {
        "APP_ID": "cf9e7264",
        "CHANNEL_NAME": "Production",
        "UPDATE_METHOD": "auto",
        "WARN_DEBUG": "true",
        "UPDATE_API": "https://api.ionicjs.com",
        "MAX_STORE": "1",
        "MIN_BACKGROUND_DURATION": "30"
      }
    },
    "platforms": [
      "ios",
      "android"
    ]
  }

**Comment by 2mia** [comment]
@nphyatt - no, i'm using `none` as the method. I want to have control when updates are downloaded/extracted.

**Comment by diegozuber** [comment]
@nphyatt i'm also using `none` as the update method.

**Comment by nphyatt** [comment]
@mikeciavHB I the the issue you’re experiencing is #121 which should be fixed by upgrading to `5.0.9`

**Comment by mikeciavHB** [comment]
Thank you very much !!! 
5.0.9 fixed my issue

**Comment by nphyatt** [comment]
UPDATE: After talking with the team who works on this plugin as well as the `cordova-plugin-ionic-webview` plugin we're going to take a hybrid approach to solve this issue and make sure that no one can accidentally brick their app. Here is the approach:

The webview plugin will expose a `persistVersion` function which will tell it to store the current version as the version to serve going forward. This means that after the `persistVersion` function is called The webview plugin will no longer serve the original bundled version and then reload using the updated version but instead load the updated version immediately. However to ensure that no one can launch a live update that is broken and can't be recovered from the deploy plugin will only call the function when the new version of the app is up and running to ensure a bad update is not persisted. This means that on the first open it will load the last version and then redirect to the new one but on subsequent updates the new one will load and therefore avoid delays & double redirects. I plan to begin working on this today so hopefully is suits everyones needs.

**Comment by flyingwip** [comment]
Tanx @nphyatt . Good to see so many response. Unfortunately I did not have the time to implement the update changes yet. Due to a deadline I had to remove the plugin for the current release. Hopefully I find time later this week.

**Comment by nphyatt** [comment]
@flyingwip @diegozuber @ibnclaudius I just cut a couple pre-releases that work in the way I described above.

The very first time a new version is run the original version will load first then redirect to the new version and assuming the new version loads it will call `persist` and then subsequent opens will open directly to the new version. 

If you'd be willing to test the updates and let me know if if solves your issues that'd be great. Then I can cut an official release for both plugins. You'll need to update both plugins to the `next` tag.

`cordova-plugin-ionic-webview@next` (`2.1.0-0`)
`cordova-plugin-ionic@next` (`5.0.11-0`)

**Comment by nphyatt** [comment]
Released `cordova-plugin-ionic-webview@2.1.0` & `cordova-plugin-ionic@5.1.0` which include the functionality I describe above but the new `cordova-plugin-ionic` adds a cordova hook to `before_build` which as long as you have the Ionic CLI >= 4.x installed will generate a manifest of the bundled app files in your binary that the plugin can read to populate the file cache an take advantage of caching from the very first update (previous versions downloaded every file of the first update and then subsequent downloads could take advantage of caching and were much faster) this means that your very first update should be much faster than it was before assuming that many of the assets/etc. were a cache hit. 

NOTE: that since this is a `before_build` hook it probably will not run before launching in the emulator. You can generate the manifest file yourself when testing by running `ionic deploy manifest` in the root of you app before running on the emulator.

**Comment by JustasKuizinas** [comment]
Still not working,  I have  cordova-plugin-ionic 5.1.2 and after each app start I have to wait for 15-20sec splash  screen and then app starts.

**Comment by 2mia** [comment]
@nphyatt works 5.1.2 works fine on device => single app initialization, that good.
It only works on first on simulator though => see https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/157

**Comment by nphyatt** [comment]
Thanks @2mia & @JustasKuizinas I've made some more optimizations as it turns out the `cordova-plugin-file` we use to write and move things tends to be slow so we've reworked a lot of the logic to use it as little as possible. We've cut a pre release `5.1.4-0` `cordova-plugin-ionic@next` which requires the `cordova-plugin-file-transfer` as well and uses that to download/write the files as it does both in native land and the overhead of passing the files across the cordova bridge was causing slow downs. We'll be cutting a new version of `cordova-plugin-ionic-webview` @2mia hopefully today and that should address the issues of rerunning on the emulator.

**Comment by flyingwip** [comment]
I am trying to install the cordova-plugin-ionic on my macbook but i keep getting this error. Also the @next or @5.1.0 or @5.1.4-0.

Failed to restore plugin "cordova-plugin-ionic" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-ionic@^5.1.5 via registry.

**Comment by nphyatt** [comment]
@flyingwip the `latest` version should now be the most up to date. I would try running `cordova plugin rm cordova-plugin-ionic` and then re-adding it and you should get the latest version...same with `cordova-plugin-ionic-webview`

**Comment by JustasKuizinas** [comment]
Is it possible to turn off plugin when running "ionic cordova plugin run android" ? Now when I open the app it applies latest snapshot and I dont see my changes

**Comment by JustasKuizinas** [comment]
> @JustasKuizinas we just cut `cordova-plugin-ionic@5.2.0` and `cordova-plugin-ionic-webview@2.1.4` if you install both of these you'll see a preference in `config.xml` called `DisableDeploy` set this to `true | false` and run `cordova prepare [platform]` to toggle between disabling and enabling deploy for development. Official docs will be updated soon.

Awsome thanks!

**Comment by jcesarmobile** [comment]
The issue seems to be fixed, so going to close it.

@flyingwip if you are able to finally test latest versions of ionic and webview plugins and still face the problem, please create a new issue.

A note about the `DisableDeploy`. The plugin adds it to the resulting config.xml with false value, but if you want to change the value to true you have to add the preference to your root config.xml and the prepare command will take care of replacing the default value from false to the value in your config.xml. So you have to manually add this preference in your config.xml to disable the plugin. `<preference name="DisableDeploy" value="true" />`

**Comment by nphyatt** [comment]
@JustasKuizinas Following up with [docs link](https://ionicframework.com/docs/pro/deploy/api/#plugin-preferences) in case you need it 😄
