### ISSUE TITLE
Deploy Randomly Stopped Working

### ISSUE THREAD

**Issue by tmyers97** [ionic-team/cordova-plugin-ionic#78]
The Live Deploy feature has been working for me for about a month and a half now then out of nowhere this week it completely stopped working. It will not update no matter what I do. I even tried creating a new fresh project and it was the same result. I do not get any errors and the deploy number on my account still goes up. Just no updates.

What can I do from here?
Thanks.

**Comment by wadedos** [comment]
I also have the same problem. Are you experiencing this with both iOS and Android ?

**Comment by tmyers97** [comment]
Yea it doesn't work on both platforms. I just tried updating manually rather than using auto and the page would refresh but still no update.

**Comment by wadedos** [comment]
I've also tried manual. My .info() API call confirms the new version is installed by the UUID, but the actual changes haven't applied. 

How far have you got with debugging it ?

What version of cordova-plugin-ionic and cordova-plugin-ionic-webview are you using ?

**Comment by karlvd** [comment]
I experience this problem as well.

To reproduce
1. Install the most basic ionic project using ionic start
2. Add deploy following the instructions in the wizard and on Ionic Pro
3. The deploy will fails with
`Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)`

I have tested downgrading both cordova and ionic without success.
I have also tested downgrading such as cordova-plugin-ionic and what´s the few plugins in the template project, still get the same result.

I am testing on iOS 11.3 (latest)

The error seems to occur in **IonicDeploy.m** on row **635**
` [self.webViewEngine loadRequest:[NSURLRequest requestWithURL:components.URL]];`

This row seems to load the newly deployed app.

Also tried reverting to UIWebView but without success
`<preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />`

**Comment by tmyers97** [comment]
`<plugin name="cordova-plugin-ionic" spec="^4.1.3">`
`<plugin name="cordova-plugin-ionic-webview" spec="^1.2.0" />`

I am also on iOS 11.3 and I have also tried on an Android emulator.

**Comment by tmyers97** [comment]
Debugged Android again with the manual updates and I get
`ERROR Error: Uncaught (in promise): /data/user/0/app.identifier/files/www.zip (No such file or directory)`

**Comment by media4learning** [comment]
+1 from me - the plugin works on iOS but on Android it stops at extracting : 95%

**Comment by wadedos** [comment]
@media4learning What versions of cordova-plugin-ionic and cordova-plugin-ionic-webview are you using ?

**Comment by saral2** [comment]
I am also facing the same issue on Android, I am using cordova-plugin-ionic: 4.1.3 and not using the webview plugin.

Error log showing this message.

04-11 18:12:24.125: I/IONIC.DEPLOY.REDIRECT(9362): Pre-redirect cordova injection exception: java.io.FileNotFoundException: /data/user/0/*****/app_5d47bf47-24f4-415b-8958-4a231dc5a279/index.html (No such file or directory)

**Comment by media4learning** [comment]
@wadedos 
"cordova-plugin-ionic": "^4.1.3",
"cordova-plugin-ionic-webview": "^1.2.0",

Note iOS is fine, just Android won't extract fully. Also worth noting, if I force close the app and reopen, it loads the new deployed content. But that's not really helpful.

**Comment by wadedos** [comment]
@media4learning I'm running the same plugin versions, and getting the same error as @karlvd. What iOS version are you testing on ? Im using iOS 11.3

`MyApp[1491:386215] Redirecting to: file:/var/mobile/Containers/Data/Application/<bundle_id>/Library/Application%20Support/<bundle_id>/index.html?cordova_js_bootstrap_resource=/var/containers/Bundle/Application/<bundle_id>/MyApp.app/www/cordova.js
MyApp[1491:386080] Reloading the web view.
MyApp[1491:386080] Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)`

**Comment by connor-odoherty** [comment]
As I've repeated elsewhere, I'm having a similar issue. With cordova-plugin-ionic-webview at 1.2.0, I get the redirect but the snapshot never applies. Downgrading to 1.1.16 applies the snapshot, but reverts to the original binary after killing and restarting the app.

This is all happening after the most recent upgrades

**Comment by tmyers97** [comment]
Downgrading didn't seem to work for me

**Comment by connor-odoherty** [comment]
@tmyers97 I think I replied to your comment on the Ionic support boards, but downgrading cordova-plugin-ionic as well to 4.0.1 finally fixed it.

However, they just released 4.1.4, which might also fix your issue.

Just remember that you should probably uninstall and remove your current cordova-plugin-ionic, and add the proper version plugin back in

**Comment by tmyers97** [comment]
No good on updating or downgrading, but good to see they are pushing out updates.

**Comment by HugoHeneault** [comment]
They are working on a v5 branch right now. It seems to be a fresh rewrite of everything, so I think we'll just have to be patient...

This issue seems to be related to https://github.com/ionic-team/cordova-plugin-ionic/issues/60 and https://github.com/ionic-team/cordova-plugin-ionic/issues/76

**Comment by Fuiste** [comment]
@HugoHeneault you are correct that we've been heads down on a full rewrite of the plugin for v5, which should fix many of the issues as well as add a bunch of new features!  Sorry for the radio silence there, it's been pretty busy recently :) 

As to everyone else experiencing issues related to plugin versions and the Ionic webview plugin, you are correct that version `1.2.0` of `cordova-plugin-ionic-webview` was not playing nice with the deploy service.  It made changes to the way the local webserver hosted up files, and as a result broke redirects for the plugin version 4.x.

To address this, we've changed the Ionic starters to ship with version `1.1.19` of the webview plugin while we get v5 into a stable beta release as soon as possible.  Going forward, we've released `4.1.6` of this plugin, which addresses another issue in the extract function and should play nice with webview `1.1.19`.

**Comment by karlvd** [comment]
For your info, the 1.2.0 version was published to npm but never published as a release on Github (still missing). This made it harder to troubleshoot since the date of releases in Github is goto source for troubleshooting.

Github
https://github.com/ionic-team/cordova-plugin-ionic-webview/releases

NPM
https://www.npmjs.com/package/cordova-plugin-ionic-webview

Not sure if it´s a mistake but I would suggest keeping npm and GitHub releases consistent. And for now it would probably be good to publish the 1.1.19 code as 1.2.1 on both Github and npm.

v1.2.0 of cordova-plugin-ionic-webview breaks MS hot-code-push as well which is similar to ionic deploy.

**Comment by tmyers97** [comment]
cordova-plugin-ionic: 4.1.6
cordova-plugin-ionic-webview: 1.1.19

Update Method: AUTO
Tested on device running iOS 11.3

Updates still not working, tried my current project and a fresh one.

**Comment by ltm** [comment]
@tmyers97 Could you post the output of the console log for your app?

**Comment by tmyers97** [comment]
Downgrading to 1.1.19 does work. It was an error on my part. I had to delete the carrot on  ^1.1.19 in my package and config files.

**Comment by DennisSmolek** [comment]
I'm still having this issue. I've tried most fixes, I'm now trying 4.0.1 and 1.19

My native build works well, I release and the deployment seems solid, the app unzips, then throws errors. started with missing cordova.js but its the same errors as posted
```
Redirecting to: file:/var/mobile/Containers/Data/Application/6BFA76E3-5072-44E6-A1CF-9C070F0ED494/Library/Application%20Support/daa31c97-2c22-4985-8e28-6f727e0a2383/index.html?cordova_js_bootstrap_resource=/var/containers/Bundle/Application/B7E6109B-0F9B-45A6-9895-0F96406FAB3E/Roam%20Showman.app/www/cordova.js
2018-06-18 15:49:17.552399-0500 Roam Showman[749:174673] Reloading the web view.
2018-06-18 15:49:17.649628-0500 Roam Showman[749:174673] Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)
```

**Comment by glebmachine** [comment]
Approve, still don't work
>     "cordova-plugin-ionic": "4.1.6",
>     "cordova-plugin-ionic-webview": "1.1.19",
